### ISSUE TITLE
NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by geekchen007** [khaotik/DaNet-Tensorflow#3]
I make sure download and install the timit dataset

  File "app/datasets/timit.py", line 102, in install_and_load
    raise FileNotFoundError(

NameError: global name 'FileNotFoundError' is not defined
![image](https://user-images.githubusercontent.com/9989714/29167441-05eeead0-7dfd-11e7-8047-14955005a1d6.png)
IOError: [Errno 2] No such file or directory: 'app/datasets/TIMIT/train_set.pkl'

**Comment by khaotik** [comment]
Did you run `install.sh`? Did it return normally? The script lacks a bit automaton, so gotta do it manually atm.

**Comment by geekchen007** [comment]
when i run install.sh,linux shell disp"bad substitution"
I find sndfile-convert  function is converts a sound files from one format to another.
how to explain"sndfile-convert $file ${file,,}"
![image](https://user-images.githubusercontent.com/9989714/29513449-fa9c468e-8697-11e7-9f82-30f74488af88.png)
